$(document).ready(function () {indexDict['en'] = [{ "title" : "Introduction to Arria for BI ", 
"url" : "introduction-to-arria-for-bi.html", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for BI ", 
"snippet" : "This topic is completely generic, so can be used exactly as-is in any of the Arria for BI courses with no filtering or variables.   Arria for BI is a suite of Arria Studio integrations, designed to... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore...", 
"body" : "This topic is completely generic, so can be used exactly as-is in any of the Arria for BI courses with no filtering or variables.   Arria for BI is a suite of Arria Studio integrations, designed to... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo kumquat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo kumquat. " }, 
{ "title" : "Introduction to Arria for Arria for Power BI ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI ", 
"snippet" : "I've created this to demonstrate how one topic that includes BI tool-specific information can be used in any Arria for BI publication (e.g. Arria for MicroStrategy and Arria for Power BI ) by using variables and filters. I'll also demonstrate the reuse of content components (paragraphs, sub-topics, ...", 
"body" : "I've created this to demonstrate how one topic that includes BI tool-specific information can be used in any Arria for BI publication (e.g. Arria for MicroStrategy and Arria for Power BI ) by using variables and filters. I'll also demonstrate the reuse of content components (paragraphs, sub-topics, notes, etc.) Product names & terminologyImagesProceduresSub-topicsReused content" }, 
{ "title" : "Product names & terminology ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#product-names---terminology", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Product names & terminology ", 
"snippet" : "Name of the Arria integration: Arria for Power BI . BI tool name: Power BI . BI tool project term: report . BI tool plug-in term: custom visual ....", 
"body" : "Name of the Arria integration: Arria for Power BI . BI tool name: Power BI . BI tool project term: report . BI tool plug-in term: custom visual . " }, 
{ "title" : "Images ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#images", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Images ", 
"snippet" : "Here's an image of the BI tool logo using an image variable. In this case, an inline image variable: Another way of doing this is to use filters:...", 
"body" : "Here's an image of the BI tool logo using an image variable. In this case, an inline image variable: Another way of doing this is to use filters: " }, 
{ "title" : "Procedures ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#procedures", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Procedures ", 
"snippet" : "Step 1: This step is required for all Arria for BI integrations. Step 2: So is this step! Step 3: This step is only required if you're using PowerBI . Step 4: This step is required for all Arria for BI integrations....", 
"body" : "Step 1: This step is required for all Arria for BI integrations. Step 2: So is this step! Step 3: This step is only required if you're using PowerBI . Step 4: This step is required for all Arria for BI integrations. " }, 
{ "title" : "Sub-topics ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#sub-topics", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Sub-topics ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Arria for Power BI ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#arria-for-power-bi", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Sub-topics \/ Arria for Power BI ", 
"snippet" : "This section contains Power BI-specific information....", 
"body" : "This section contains Power BI-specific information. " }, 
{ "title" : "Reused content ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#reused-content", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Reused content ", 
"snippet" : "This introduction to the Power BI section is a reused 'para', as you can see from the chain links icon to the left. Even though it has BI tool-specific information in it, like the name of the integration ( Arria for Power BI ), we can reuse the whole para because we're using a variable instead of th...", 
"body" : "This introduction to the Power BI section is a reused 'para', as you can see from the chain links icon to the left. Even though it has BI tool-specific information in it, like the name of the integration ( Arria for Power BI ), we can reuse the whole para because we're using a variable instead of the integration name itself. Arria is awesome REMINDER! Arria is awesome! " }, 
{ "title" : "Reused topic - definition of dimensions and measures ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#reused-topic---definition-of-dimensions-and-measures", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Reused content \/ Reused topic - definition of dimensions and measures ", 
"snippet" : "Dimensions A dimension is a categorical, qualitative field in your data, such as Segment or Product. A time dimension is a particular type of dimension that contains date values. You can use time dimensions to analyze your data by year, quarter, month, or day.   Measures A measure is a numeric, quan...", 
"body" : "Dimensions A dimension is a categorical, qualitative field in your data, such as Segment or Product. A time dimension is a particular type of dimension that contains date values. You can use time dimensions to analyze your data by year, quarter, month, or day.   Measures A measure is a numeric, quantitative field in your data, such as Sales, Profit, or Temperature. " }, 
{ "title" : "Support ", 
"url" : "introduction-to-arria-for-arria-for-power-bi.html#support", 
"breadcrumbs" : "Arria for Power BI demo \/ Introduction to Arria for Arria for Power BI \/ Reused content \/ Support ", 
"snippet" : "Questions? We're here to help!...", 
"body" : "Questions? We're here to help! " }, 
{ "title" : "Installing Power BI ", 
"url" : "installing-power-bi.html", 
"breadcrumbs" : "Arria for Power BI demo \/ Installing Power BI ", 
"snippet" : "Because this section is highly specific to Arria for Power BI, it's not reused in any other Arria for BI course. However, this one paragraph is useful for all Arria for BI products and is reused in each of them. It's the only piece of reused content in this topic....", 
"body" : "Because this section is highly specific to Arria for Power BI, it's not reused in any other Arria for BI course. However, this one paragraph is useful for all Arria for BI products and is reused in each of them. It's the only piece of reused content in this topic. " }, 
{ "title" : "Import Arria for Power BI ", 
"url" : "installing-power-bi.html#import-arria-for-power-bi", 
"breadcrumbs" : "Arria for Power BI demo \/ Installing Power BI \/ Import Arria for Power BI ", 
"snippet" : "In Power BI, open a report. On the right-hand side of the report, in the Visualizations pane, click the Get more visuals ellipsis: Choose one of the following import options: Arria-Hosted Public Cloud deployments only : To import Arria for Power BI from Microsoft AppSource, select  Get more visuals ...", 
"body" : "In Power BI, open a report. On the right-hand side of the report, in the Visualizations pane, click the Get more visuals ellipsis: Choose one of the following import options: Arria-Hosted Public Cloud deployments only : To import Arria for Power BI from Microsoft AppSource, select  Get more visuals . Find the Arria visual by searching on “Arria”, then click  Add . Arria-Hosted Public Cloud, Arria-Hosted Private Cloud, and Customer-Hosted deployments : To import Arria for Power BI from a previously downloaded PBIVIZ file , select Import a visual from a file . Browse to find the file on your computer, then click Open . The directions for downloading Arria for Power BI depend on your chosen deployment option : Arria-Hosted Public Cloud deployments On the Arria website , sign in to your Arria account and download the Arria for Power BI visual ( .pbiviz file). Arria-Hosted Private Cloud and Customer-Hosted deployments Users of the Arria-Hosted Private Cloud (a.k.a. Dedicated Cloud) and Customer-Hosted (a.k.a. On-Premises) deployment options can no longer use the publicly available Arria for Power BI custom visual. Instead, a unique instance of the visual configured to call your exclusive Arria for Power BI services, must be installed. Contact Arria or your systems administrator for details. A message is displayed to indicate that the visual has been successfully imported. Click OK . The Arria logo appears in your Visualization pane. Make sure to click off any charts in your report. If you have a chart selected during the next step, it will be overwritten. Click the Arria logo icon to add the visual to your report. Move and resize it as desired. Top " }
]
$(document).trigger('search.ready');
});